backend:
  name: github
  repo: vin1026/createobsession-website
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "tutorials"
    label: "Tutorials"
    folder: "content/tutorials"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { 
          label: "Difficulty Level", 
          name: "difficulty", 
          widget: "select", 
          options: ["Beginner", "Intermediate", "Advanced"] 
        }
      - { label: "Duration (minutes)", name: "duration", widget: "number" }
      - { label: "Content", name: "body", widget: "markdown" } 